# Generated by Django 3.2.10 on 2021-12-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securelifeapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='time',
        ),
    ]
