# Generated by Django 3.2.10 on 2021-12-10 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securelifeapi', '0002_remove_adventure_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacesVisited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_visited', to='securelifeapi.adventure')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_visited', to='securelifeapi.location')),
            ],
        ),
    ]
