# Generated by Django 3.2.10 on 2021-12-14 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securelifeapi', '0003_placesvisited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='image',
        ),
    ]
