# Generated by Django 3.2.10 on 2021-12-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securelifeapi', '0004_remove_adventure_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='user',
        ),
    ]
