# Generated by Django 3.2.10 on 2021-12-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securelifeapi', '0006_auto_20211214_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='park',
            field=models.CharField(max_length=100),
        ),
    ]
