# Generated by Django 3.2.10 on 2021-12-15 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securelifeapi', '0007_auto_20211215_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Growth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('length', models.IntegerField()),
                ('date', models.DateField()),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth', to='securelifeapi.human')),
            ],
        ),
        migrations.DeleteModel(
            name='HumanProgress',
        ),
    ]
