# Generated by Django 3.2.10 on 2021-12-16 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securelifeapi', '0008_auto_20211215_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='date',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='image',
            name='tag',
        ),
        migrations.AddField(
            model_name='image',
            name='action_pic',
            field=models.ImageField(null=True, upload_to='adventureimages'),
        ),
        migrations.AddField(
            model_name='image',
            name='adventure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='securelifeapi.adventure'),
            preserve_default=False,
        ),
    ]
