# Generated by Django 3.2.10 on 2021-12-20 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securelifeapi', '0010_alter_image_adventure'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_pic', models.ImageField(null=True, upload_to='growthimages')),
                ('growth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='securelifeapi.growth')),
            ],
        ),
    ]
