# Generated by Django 3.2.10 on 2021-12-20 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securelifeapi', '0011_growthimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growthimage',
            name='growth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_images', to='securelifeapi.growth'),
        ),
    ]
