# Generated by Django 3.2.10 on 2021-12-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securelifeapi', '0012_alter_growthimage_growth'),
    ]

    operations = [
        migrations.AddField(
            model_name='growth',
            name='notes',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
