# Generated by Django 3.2.10 on 2021-12-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securelifeapi', '0013_growth_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='growth',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
