# Generated by Django 3.2.10 on 2021-12-22 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securelifeapi', '0014_growth_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='locations',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adventure', to='securelifeapi.location'),
            preserve_default=False,
        ),
    ]
