# Generated by Django 3.2.10 on 2021-12-22 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securelifeapi', '0016_rename_locations_adventure_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventures', to='securelifeapi.location'),
        ),
    ]
