# Generated by Django 3.2.10 on 2021-12-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securelifeapi', '0017_alter_adventure_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='location',
        ),
        migrations.AddField(
            model_name='adventure',
            name='location',
            field=models.ManyToManyField(through='securelifeapi.PlacesVisited', to='securelifeapi.Location'),
        ),
    ]
