# Generated by Django 3.2.10 on 2021-12-22 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securelifeapi', '0018_auto_20211222_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='location',
        ),
        migrations.AddField(
            model_name='adventure',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adventures', to='securelifeapi.location'),
            preserve_default=False,
        ),
    ]
