# Generated by Django 3.2.10 on 2021-12-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securelifeapi', '0021_rename_locations_adventure_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
    ]
