# Generated by Django 3.2.10 on 2021-12-31 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securelifeapi', '0024_auto_20211230_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='user',
        ),
        migrations.AddField(
            model_name='city',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='securelifeapi.creator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='securelifeapi.creator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='securelifeapi.creator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='growth',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='securelifeapi.creator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='human',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='securelifeapi.creator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='securelifeapi.creator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='securelifeapi.creator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='park',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='securelifeapi.creator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='securelifeapi.creator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placesvisited',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='securelifeapi.creator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='securelifeapi.creator'),
            preserve_default=False,
        ),
    ]
