# Generated by Django 3.2.10 on 2021-12-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securelifeapi', '0025_auto_20211231_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
