# Generated by Django 3.2.10 on 2021-12-31 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securelifeapi', '0026_alter_park_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='image',
        ),
    ]
