# Generated by Django 3.2.10 on 2021-12-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securelifeapi', '0027_remove_journalentry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='entry',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
