# Generated by Django 3.2.10 on 2021-12-31 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securelifeapi', '0029_alter_city_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='creator',
        ),
    ]
