# Generated by Django 3.2.10 on 2021-12-31 22:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('securelifeapi', '0030_remove_participant_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='human',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 12, 31, 22, 57, 53, 961575, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
