# Generated by Django 3.2.10 on 2022-01-04 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securelifeapi', '0031_auto_20211231_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_pic', models.ImageField(null=True, upload_to='humanimages')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_images', to='securelifeapi.human')),
            ],
        ),
    ]
